# Generated by Django 5.0 on 2024-03-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=120)),
                ('Password', models.CharField(max_length=50)),
                ('Dob', models.DateField()),
                ('Image', models.ImageField(upload_to='auth/images')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
